// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu00K3rWa3sFj88gwWsmKsPN83V8Gn6io',
    appId: '1:380244150098:web:291ce78bf432e5d8345c8b',
    messagingSenderId: '380244150098',
    projectId: 'ecomm-285ef',
    authDomain: 'ecomm-285ef.firebaseapp.com',
    storageBucket: 'ecomm-285ef.firebasestorage.app',
    measurementId: 'G-9RD6Q4B70G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCriBUmQqQE0JaEFGcmCL5U1K34yVnPCcI',
    appId: '1:380244150098:android:b4678ab1d95808a6345c8b',
    messagingSenderId: '380244150098',
    projectId: 'ecomm-285ef',
    storageBucket: 'ecomm-285ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW2p3OscjoAAUcDhBvX6sib79TrAUOhQ0',
    appId: '1:55065289851:ios:17e8167707f8b56b1beede',
    messagingSenderId: '55065289851',
    projectId: 'easyshopping-ce06a',
    storageBucket: 'easyshopping-ce06a.appspot.com',
    androidClientId: '55065289851-1f51ij157meofng9631tfhf3l77d6m2t.apps.googleusercontent.com',
    iosClientId: '55065289851-jd80ie06tp57qdear8q2fsodntvvsli0.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW2p3OscjoAAUcDhBvX6sib79TrAUOhQ0',
    appId: '1:55065289851:ios:451ec35cba3a6c5a1beede',
    messagingSenderId: '55065289851',
    projectId: 'easyshopping-ce06a',
    storageBucket: 'easyshopping-ce06a.appspot.com',
    androidClientId: '55065289851-1f51ij157meofng9631tfhf3l77d6m2t.apps.googleusercontent.com',
    iosClientId: '55065289851-fgejku052n5r4ognssmg6hgbu16g14rd.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminPanel.RunnerTests',
  );
}